#!/usr/bin/env python3
"""Generate src/sparktlscrypto-p256-fixed_base.ads: the fixed-base table for
P-256 generator multiplication with Booth-recoded 7-bit windows.

Entry (i, j - 1) is the affine point j * 2^(7 i) * G for i in 0 .. 45 and
j in 1 .. 64, coordinates in the Montgomery domain of SPARKTLSCrypto.Fiat_P256
(x * 2^256 mod p), four little-endian 64-bit limbs each, matching the
existing Comb_G table in sparktlscrypto-p256-point.adb. Pure-integer affine
arithmetic; every point is checked on the curve before emission, and the
first entry is checked against the published generator.
"""
p  = 0xFFFFFFFF00000001000000000000000000000000FFFFFFFFFFFFFFFFFFFFFFFF
a  = p - 3
b  = 0x5AC635D8AA3A93E7B3EBBD55769886BC651D06B0CC53B0F63BCE3C3E27D2604B
Gx = 0x6B17D1F2E12C4247F8BCE6E563A440F277037D812DEB33A0F4A13945D898C296
Gy = 0x4FE342E2FE1A7F9B8EE7EB4A7C0F9E162BCE33576B315ECECBB6406837BF51F5
n  = 0xFFFFFFFF00000000FFFFFFFFFFFFFFFFBCE6FAADA7179E84F3B9CAC2FC632551
R  = 1 << 256

def inv(x): return pow(x, p - 2, p)
def on_curve(P):
    x, y = P; return (y * y - (x * x * x + a * x + b)) % p == 0
def add(P, Q):
    if P is None: return Q
    if Q is None: return P
    x1, y1 = P; x2, y2 = Q
    if x1 == x2:
        if (y1 + y2) % p == 0: return None
        l = (3 * x1 * x1 + a) * inv(2 * y1) % p
    else:
        l = (y2 - y1) * inv(x2 - x1) % p
    x3 = (l * l - x1 - x2) % p
    return (x3, (l * (x1 - x3) - y1) % p)
def dbl(P): return add(P, P)
def mont(x): return x * R % p
def limbs(x): return [(x >> (64 * k)) & (2**64 - 1) for k in range(4)]
def fmt(x):
    ls = limbs(x)
    return ", ".join("16#%016X#" % v for v in ls)

G = (Gx, Gy)
assert on_curve(G)
assert limbs(mont(Gx))[0] == 0x79E730D418A9143C, "Montgomery form disagrees with Comb_G (1)"

rows = []
base = G
for i in range(46):
    Pt = None
    row = []
    for j in range(1, 65):
        Pt = add(Pt, base)
        assert Pt is not None and on_curve(Pt)
        row.append(Pt)
    rows.append(row)
    for _ in range(7):
        base = dbl(base)

out = []
out.append("--  Fixed-base table for P-256 generator multiplication.")
out.append("--  GENERATED by tools/gen_p256_fixed_base.py; do not edit by hand.")
out.append("--")
out.append("--  Entry (I, J - 1) is the affine point J * 2^(7 * I) * G, I in 0 .. 36,")
out.append("--  J in 1 .. 64, in the Montgomery domain of Fiat_P256 (x * 2^256 mod p),")
out.append("--  little-endian limbs. With Booth-recoded 7-bit windows a 256-bit")
out.append("--  scalar is a signed digit d_i in -64 .. 64 per window, k = sum d_i *")
out.append("--  2^(7 i), so [k]G is one lookup (negate y for a negative digit) and")
out.append("--  one mixed addition per window, no doublings. 46 windows cover 322")
out.append("--  bits: a 256-bit scalar blinded as k + r * n with a 64-bit r (SR-62).")
out.append("--  Every point was checked on the curve at")
out.append("--  generation; the generator entry matches the Comb_G table.")
out.append("")
out.append("with SPARKTLSCrypto.P256; use SPARKTLSCrypto.P256;")
out.append("")
out.append("package SPARKTLSCrypto.P256.Fixed_Base with")
out.append("   SPARK_Mode => On")
out.append("is")
out.append("   type Affine_Mont is record")
out.append("      X : P256_FE;")
out.append("      Y : P256_FE;")
out.append("   end record;")
out.append("")
out.append("   subtype Window_Index is Natural range 0 .. 45;")
out.append("   subtype Entry_Index  is Natural range 0 .. 63;")
out.append("   type Window_Row  is array (Entry_Index) of Affine_Mont;")
out.append("   type Fixed_Table is array (Window_Index) of Window_Row;")
out.append("")
out.append("   --  Deferred: the 2368 points are completed in the private part with")
out.append("   --  SPARK_Mode Off, so proof sees a constant of this type and never the")
out.append("   --  data (which otherwise reaches the solvers as thousands of axioms and")
out.append("   --  stalls the proof of every unit that reads it). Correctness of the")
out.append("   --  values is established by the generator's on-curve checks and by the")
out.append("   --  ECDSA test vectors, not by proof.")
out.append("   Fixed_G : constant Fixed_Table;")
out.append("")
out.append("private")
out.append("   pragma SPARK_Mode (Off);")
out.append("")
out.append("   Fixed_G : constant Fixed_Table := (")
for i, row in enumerate(rows):
    out.append("      %d => (" % i)
    for j, (x, y) in enumerate(row):
        sep = "," if j < 63 else ""
        out.append("         %d => (X => (%s)," % (j, fmt(mont(x))))
        out.append("               Y => (%s))%s" % (fmt(mont(y)), sep))
    out.append("      )%s" % ("," if i < 45 else ""))
out.append("   );")
out.append("")
out.append("end SPARKTLSCrypto.P256.Fixed_Base;")
open("src/sparktlscrypto-p256-fixed_base.ads", "w").write("\n".join(out) + "\n")
print("wrote", 37 * 64, "points")
