#!/usr/bin/env python3
"""Generate public [k * 256**position]B constants with integer arithmetic."""
import argparse
from pathlib import Path

P = 2**255 - 19
D = -121665 * pow(121666, -1, P) % P
B = (
    15112221349535400772501151409588531511454012693041857206046113283949847762202,
    46316835694926478169428394003475163141307993866256225615783033603165251855960,
)


def add(left, right):
    x, y = left
    u, v = right
    product = D * x * u * y * v % P
    return (
        (x * v + y * u) * pow(1 + product, -1, P) % P,
        (y * v + x * u) * pow(1 - product, -1, P) % P,
    )


def valid(point):
    x, y = point
    return (-x * x + y * y - 1 - D * x * x * y * y) % P == 0


def limbs(value):
    words = (f"16#{(value >> (51 * i)) & (2**51 - 1):013X}#" for i in range(5))
    return "(" + ", ".join(words) + ")"


def render():
    specification = """--  Generated by tools/generate_ed25519_base.py; do not edit.
--  Table (i, k) = [k * 256**i]B as (Y+X, Y-X, 2*d*X*Y).
with Interfaces; use Interfaces;
package SPARKTLSCrypto.Ed25519_Base_Table with SPARK_Mode => On is
   subtype Position is Natural range 0 .. 31;
   subtype Digit is Natural range 1 .. 15;
   subtype Nibble is Unsigned_64 range 0 .. 15;
   subtype Limb is Unsigned_64 range 0 .. 16#7_FFFF_FFFF_FFFF#;
   type Coordinate is array (Natural range 0 .. 4) of Limb;
   type Cached_Point is record
      Y_Plus_X, Y_Minus_X, XY2D : Coordinate;
   end record;
   type Point_Row is array (Digit) of Cached_Point;
   --  I is public; K is secret. Scan every entry of the selected row.
   function Lookup (I : Position; K : Nibble) return Cached_Point
     with Global => null;
end SPARKTLSCrypto.Ed25519_Base_Table;
"""
    lines = [
        "--  Generated by tools/generate_ed25519_base.py; do not edit.",
        "with SPARKTLSCrypto.Ed25519_Base_Scan;",
        "package body SPARKTLSCrypto.Ed25519_Base_Table with SPARK_Mode => On is",
        "   subtype Row is Point_Row;",
    ]
    base = B
    # Separate constant rows avoid costly expansion of a large initializer
    # in GNATprove. Dispatch depends only on the public byte position.
    for position in range(32):
        point = (0, 1)
        lines.append(f"   Row_{position} : constant Row := (")
        for digit in range(1, 16):
            point = add(point, base)
            if not valid(point):
                raise ValueError(f"off-curve point at position {position}, digit {digit}")
            x, y = point
            lines.extend([
                f"         {digit} => (Y_Plus_X => {limbs((y + x) % P)},",
                f"                Y_Minus_X => {limbs((y - x) % P)},",
                f"                XY2D => {limbs(2 * D * x * y % P)})" + ("," if digit < 15 else ""),
            ])
        lines.append("   );")
        for _ in range(8):
            base = add(base, base)
    lines.extend([
        "   function Lookup (I : Position; K : Nibble) return Cached_Point is",
        "   begin",
        "      case I is",
        *[f"         when {i} => return Ed25519_Base_Scan.Select_Point (Row_{i}, K);" for i in range(32)],
        "      end case;",
        "   end Lookup;",
        "end SPARKTLSCrypto.Ed25519_Base_Table;",
        "",
    ])
    return specification, "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    parser.add_argument(
        "--output", type=Path,
        default=Path(__file__).resolve().parents[1] / "src/sparktlscrypto-ed25519_base_table.ads",
    )
    args = parser.parse_args()
    if args.output.suffix != ".ads":
        parser.error("--output must name the .ads specification")
    specification, body = render()
    body_path = args.output.with_suffix(".adb")
    if args.check:
        if args.output.read_text() != specification or body_path.read_text() != body:
            raise SystemExit("base table differs from generator")
        print("480 public base points regenerated and checked")
    else:
        args.output.write_text(specification)
        body_path.write_text(body)


if __name__ == "__main__":
    main()
