--  SPARKTLS Fiat P-256 — Faithful port of fiat-crypto p256_64.c
--
--  Original: https://github.com/mit-plv/fiat-crypto
--  Generated by: 'src/ExtractionOCaml/word_by_word_montgomery' --inline
--    --static --use-value-barrier p256 64 '2^256 - 2^224 + 2^192 + 2^96 - 1'
--
--  Every function is a line-by-line translation of the Coq-verified C output.
--  The SSA form is preserved for performance (optimal register allocation).

with Interfaces; use Interfaces;

package body SPARKTLSCrypto.Fiat_P256 with
   SPARK_Mode => On
is

   ----------------------------------------------------------------
   --  Fiat primitives — direct translation of the corresponding
   --  static inline helpers in fiat-crypto's p256_64.c. Each
   --  collapses one declare-block worth of inlined Unsigned_128
   --  arithmetic into a single call.
   ----------------------------------------------------------------

   procedure Addcarryx_U64
     (Out1 : out Unsigned_64;
      Out2 : out Unsigned_64;
      Arg1 :     Unsigned_64;
      Arg2 :     Unsigned_64;
      Arg3 :     Unsigned_64)
   with Inline
   is
      X : constant Unsigned_128 :=
         Unsigned_128 (Arg1) + Unsigned_128 (Arg2) + Unsigned_128 (Arg3);
   begin
      Out1 := Unsigned_64 (X and 16#FFFF_FFFF_FFFF_FFFF#);
      Out2 := Unsigned_64 (Shift_Right (X, 64));
   end Addcarryx_U64;

   procedure Subborrowx_U64
     (Out1 : out Unsigned_64;
      Out2 : out Unsigned_64;
      Arg1 :     Unsigned_64;
      Arg2 :     Unsigned_64;
      Arg3 :     Unsigned_64)
   with Inline
   is
      X : constant Unsigned_128 :=
         Unsigned_128 (Arg2) - Unsigned_128 (Arg1) - Unsigned_128 (Arg3);
   begin
      Out1 := Unsigned_64 (X and 16#FFFF_FFFF_FFFF_FFFF#);
      Out2 := Unsigned_64 (Shift_Right (X, 64)) and 1;
   end Subborrowx_U64;

   procedure Mulx_U64
     (Out1 : out Unsigned_64;
      Out2 : out Unsigned_64;
      Arg1 :     Unsigned_64;
      Arg2 :     Unsigned_64)
   with Inline
   is
      X : constant Unsigned_128 := Unsigned_128 (Arg1) * Unsigned_128 (Arg2);
   begin
      Out1 := Unsigned_64 (X and 16#FFFF_FFFF_FFFF_FFFF#);
      Out2 := Unsigned_64 (Shift_Right (X, 64));
   end Mulx_U64;

   procedure Cmovznz_U64
     (Out1 : out Unsigned_64;
      Arg1 :     Unsigned_64;
      Arg2 :     Unsigned_64;
      Arg3 :     Unsigned_64)
   with Inline
   is
      Mask : constant Unsigned_64 :=
         -(Arg1 and 1);
   begin
      Out1 := (Mask and Arg3) or ((not Mask) and Arg2);
   end Cmovznz_U64;

   Mask64 : constant Unsigned_128 := 16#FFFF_FFFF_FFFF_FFFF#;


function Mul (Arg1, Arg2 : FE) return FE is
   Out1 : FE;
   x1, x2, x3, x4, x5, x6, x7, x8          : Unsigned_64;
   x9, x10, x11, x12, x13, x14, x15, x16    : Unsigned_64;
   x17, x18, x19, x20, x21, x22, x23, x24   : Unsigned_64;
   x25, x26, x27, x28, x29, x30, x31, x32   : Unsigned_64;
   x33, x34, x35, x36, x37, x38, x39, x40   : Unsigned_64;
   x41, x42, x43, x44, x45, x46, x47, x48   : Unsigned_64;
   x49, x50, x51, x52, x53, x54, x55, x56   : Unsigned_64;
   x57, x58, x59, x60, x61, x62, x63, x64   : Unsigned_64;
   x65, x66, x67, x68, x69, x70, x71, x72   : Unsigned_64;
   x73, x74, x75, x76, x77, x78, x79, x80   : Unsigned_64;
   x81, x82, x83, x84, x85, x86, x87, x88   : Unsigned_64;
   x89, x90, x91, x92, x93, x94, x95, x96   : Unsigned_64;
   x97, x98, x99, x100, x101, x102, x103, x104 : Unsigned_64;
   x105, x106, x107, x108, x109, x110, x111, x112 : Unsigned_64;
   x113, x114, x115, x116, x117, x118, x119, x120 : Unsigned_64;
   x121, x122, x123, x124, x125, x126, x127, x128 : Unsigned_64;
   x129, x130, x131, x132, x133, x134, x135, x136 : Unsigned_64;
   x137, x138, x139, x140, x141, x142, x143, x144 : Unsigned_64;
   x145, x146, x147, x148, x149, x150, x151, x152 : Unsigned_64;
   x153, x154, x155, x156, x157, x158, x159, x160 : Unsigned_64;
   x161, x162, x163, x164, x165, x166, x167, x168 : Unsigned_64;
   x169, x170, x171, x172, x173, x174, x175, x176 : Unsigned_64;
   x177, x178, x179, x180, x181, x182, x183, x184 : Unsigned_64;
   x185, x186, x187 : Unsigned_64;
begin
   x1 := Arg1(1);
   x2 := Arg1(2);
   x3 := Arg1(3);
   x4 := Arg1(0);

   -- iteration 1: arg1[0] * arg2
   Mulx_U64 (x5, x6, x4, Arg2(3));
   Mulx_U64 (x7, x8, x4, Arg2(2));
   Mulx_U64 (x9, x10, x4, Arg2(1));
   Mulx_U64 (x11, x12, x4, Arg2(0));
   Addcarryx_U64 (x13, x14, 0, x12, x9);
   Addcarryx_U64 (x15, x16, x14, x10, x7);
   Addcarryx_U64 (x17, x18, x16, x8, x5);
   x19 := x18 + x6;

   -- Montgomery reduction, iteration 1
   Mulx_U64 (x20, x21, x11, 16#FFFF_FFFF_0000_0001#);
   Mulx_U64 (x22, x23, x11, 16#0000_0000_FFFF_FFFF#);
   Mulx_U64 (x24, x25, x11, 16#FFFF_FFFF_FFFF_FFFF#);
   Addcarryx_U64 (x26, x27, 0, x25, x22);
   x28 := x27 + x23;
   Addcarryx_U64 (x29, x30, 0, x11, x24);
   Addcarryx_U64 (x31, x32, x30, x13, x26);
   Addcarryx_U64 (x33, x34, x32, x15, x28);
   Addcarryx_U64 (x35, x36, x34, x17, x20);
   Addcarryx_U64 (x37, x38, x36, x19, x21);

   -- iteration 2: arg1[1] * arg2
   Mulx_U64 (x39, x40, x1, Arg2(3));
   Mulx_U64 (x41, x42, x1, Arg2(2));
   Mulx_U64 (x43, x44, x1, Arg2(1));
   Mulx_U64 (x45, x46, x1, Arg2(0));
   Addcarryx_U64 (x47, x48, 0, x46, x43);
   Addcarryx_U64 (x49, x50, x48, x44, x41);
   Addcarryx_U64 (x51, x52, x50, x42, x39);
   x53 := x52 + x40;
   Addcarryx_U64 (x54, x55, 0, x31, x45);
   Addcarryx_U64 (x56, x57, x55, x33, x47);
   Addcarryx_U64 (x58, x59, x57, x35, x49);
   Addcarryx_U64 (x60, x61, x59, x37, x51);
   Addcarryx_U64 (x62, x63, x61, x38, x53);

   -- Montgomery reduction, iteration 2
   Mulx_U64 (x64, x65, x54, 16#FFFF_FFFF_0000_0001#);
   Mulx_U64 (x66, x67, x54, 16#0000_0000_FFFF_FFFF#);
   Mulx_U64 (x68, x69, x54, 16#FFFF_FFFF_FFFF_FFFF#);
   Addcarryx_U64 (x70, x71, 0, x69, x66);
   x72 := x71 + x67;
   Addcarryx_U64 (x73, x74, 0, x54, x68);
   Addcarryx_U64 (x75, x76, x74, x56, x70);
   Addcarryx_U64 (x77, x78, x76, x58, x72);
   Addcarryx_U64 (x79, x80, x78, x60, x64);
   Addcarryx_U64 (x81, x82, x80, x62, x65);
   x83 := x82 + x63;

   -- iteration 3: arg1[2] * arg2
   Mulx_U64 (x84, x85, x2, Arg2(3));
   Mulx_U64 (x86, x87, x2, Arg2(2));
   Mulx_U64 (x88, x89, x2, Arg2(1));
   Mulx_U64 (x90, x91, x2, Arg2(0));
   Addcarryx_U64 (x92, x93, 0, x91, x88);
   Addcarryx_U64 (x94, x95, x93, x89, x86);
   Addcarryx_U64 (x96, x97, x95, x87, x84);
   x98 := x97 + x85;
   Addcarryx_U64 (x99, x100, 0, x75, x90);
   Addcarryx_U64 (x101, x102, x100, x77, x92);
   Addcarryx_U64 (x103, x104, x102, x79, x94);
   Addcarryx_U64 (x105, x106, x104, x81, x96);
   Addcarryx_U64 (x107, x108, x106, x83, x98);

   -- Montgomery reduction, iteration 3
   Mulx_U64 (x109, x110, x99, 16#FFFF_FFFF_0000_0001#);
   Mulx_U64 (x111, x112, x99, 16#0000_0000_FFFF_FFFF#);
   Mulx_U64 (x113, x114, x99, 16#FFFF_FFFF_FFFF_FFFF#);
   Addcarryx_U64 (x115, x116, 0, x114, x111);
   x117 := x116 + x112;
   Addcarryx_U64 (x118, x119, 0, x99, x113);
   Addcarryx_U64 (x120, x121, x119, x101, x115);
   Addcarryx_U64 (x122, x123, x121, x103, x117);
   Addcarryx_U64 (x124, x125, x123, x105, x109);
   Addcarryx_U64 (x126, x127, x125, x107, x110);
   x128 := x127 + x108;

   -- iteration 4: arg1[3] * arg2
   Mulx_U64 (x129, x130, x3, Arg2(3));
   Mulx_U64 (x131, x132, x3, Arg2(2));
   Mulx_U64 (x133, x134, x3, Arg2(1));
   Mulx_U64 (x135, x136, x3, Arg2(0));
   Addcarryx_U64 (x137, x138, 0, x136, x133);
   Addcarryx_U64 (x139, x140, x138, x134, x131);
   Addcarryx_U64 (x141, x142, x140, x132, x129);
   x143 := x142 + x130;
   Addcarryx_U64 (x144, x145, 0, x120, x135);
   Addcarryx_U64 (x146, x147, x145, x122, x137);
   Addcarryx_U64 (x148, x149, x147, x124, x139);
   Addcarryx_U64 (x150, x151, x149, x126, x141);
   Addcarryx_U64 (x152, x153, x151, x128, x143);

   -- Montgomery reduction, iteration 4
   Mulx_U64 (x154, x155, x144, 16#FFFF_FFFF_0000_0001#);
   Mulx_U64 (x156, x157, x144, 16#0000_0000_FFFF_FFFF#);
   Mulx_U64 (x158, x159, x144, 16#FFFF_FFFF_FFFF_FFFF#);
   Addcarryx_U64 (x160, x161, 0, x159, x156);
   x162 := x161 + x157;
   Addcarryx_U64 (x163, x164, 0, x144, x158);
   Addcarryx_U64 (x165, x166, x164, x146, x160);
   Addcarryx_U64 (x167, x168, x166, x148, x162);
   Addcarryx_U64 (x169, x170, x168, x150, x154);
   Addcarryx_U64 (x171, x172, x170, x152, x155);
   x173 := x172 + x153;

   -- final conditional subtraction
   Subborrowx_U64 (x174, x175, 0, x165, 16#FFFF_FFFF_FFFF_FFFF#);
   Subborrowx_U64 (x176, x177, x175, x167, 16#0000_0000_FFFF_FFFF#);
   Subborrowx_U64 (x178, x179, x177, x169, 0);
   Subborrowx_U64 (x180, x181, x179, x171, 16#FFFF_FFFF_0000_0001#);
   Subborrowx_U64 (x182, x183, x181, x173, 0);
   Cmovznz_U64 (x184, x183, x174, x165);
   Cmovznz_U64 (x185, x183, x176, x167);
   Cmovznz_U64 (x186, x183, x178, x169);
   Cmovznz_U64 (x187, x183, x180, x171);

   Out1 := (x184, x185, x186, x187);
   return Out1;
end Mul;

function Sqr (Arg1 : FE) return FE is
   Out1 : FE;
   x1, x2, x3, x4, x5, x6, x7, x8             : Unsigned_64;
   x9, x10, x11, x12, x13, x14, x15, x16       : Unsigned_64;
   x17, x18, x19, x20, x21, x22, x23, x24      : Unsigned_64;
   x25, x26, x27, x28, x29, x30, x31, x32      : Unsigned_64;
   x33, x34, x35, x36, x37, x38, x39, x40      : Unsigned_64;
   x41, x42, x43, x44, x45, x46, x47, x48      : Unsigned_64;
   x49, x50, x51, x52, x53, x54, x55, x56      : Unsigned_64;
   x57, x58, x59, x60, x61, x62, x63, x64      : Unsigned_64;
   x65, x66, x67, x68, x69, x70, x71, x72      : Unsigned_64;
   x73, x74, x75, x76, x77, x78, x79, x80      : Unsigned_64;
   x81, x82, x83, x84, x85, x86, x87, x88      : Unsigned_64;
   x89, x90, x91, x92, x93, x94, x95, x96      : Unsigned_64;
   x97, x98, x99, x100, x101, x102, x103, x104 : Unsigned_64;
   x105, x106, x107, x108, x109, x110, x111, x112 : Unsigned_64;
   x113, x114, x115, x116, x117, x118, x119, x120 : Unsigned_64;
   x121, x122, x123, x124, x125, x126, x127, x128 : Unsigned_64;
   x129, x130, x131, x132, x133, x134, x135, x136 : Unsigned_64;
   x137, x138, x139, x140, x141, x142, x143, x144 : Unsigned_64;
   x145, x146, x147, x148, x149, x150, x151, x152 : Unsigned_64;
   x153, x154, x155, x156, x157, x158, x159, x160 : Unsigned_64;
   x161, x162, x163, x164, x165, x166, x167, x168 : Unsigned_64;
   x169, x170, x171, x172, x173, x174, x175, x176 : Unsigned_64;
   x177, x178, x179, x180, x181, x182, x183, x184 : Unsigned_64;
   x185, x186, x187                              : Unsigned_64;
begin
   -- Load arg1 limbs
   x1 := Arg1 (1);
   x2 := Arg1 (2);
   x3 := Arg1 (3);
   x4 := Arg1 (0);

   -- Round 1: multiply by x4 = arg1[0]
   Mulx_U64 (x5, x6, x4, Arg1 (3));
   Mulx_U64 (x7, x8, x4, Arg1 (2));
   Mulx_U64 (x9, x10, x4, Arg1 (1));
   Mulx_U64 (x11, x12, x4, Arg1 (0));

   Addcarryx_U64 (x13, x14, 0, x12, x9);
   Addcarryx_U64 (x15, x16, x14, x10, x7);
   Addcarryx_U64 (x17, x18, x16, x8, x5);
   x19 := x18 + x6;

   -- Montgomery reduction 1
   Mulx_U64 (x20, x21, x11, 16#FFFF_FFFF_0000_0001#);
   Mulx_U64 (x22, x23, x11, 16#0000_0000_FFFF_FFFF#);
   Mulx_U64 (x24, x25, x11, 16#FFFF_FFFF_FFFF_FFFF#);

   Addcarryx_U64 (x26, x27, 0, x25, x22);
   x28 := x27 + x23;

   Addcarryx_U64 (x29, x30, 0, x11, x24);
   Addcarryx_U64 (x31, x32, x30, x13, x26);
   Addcarryx_U64 (x33, x34, x32, x15, x28);
   Addcarryx_U64 (x35, x36, x34, x17, x20);
   Addcarryx_U64 (x37, x38, x36, x19, x21);

   -- Round 2: multiply by x1 = arg1[1]
   Mulx_U64 (x39, x40, x1, Arg1 (3));
   Mulx_U64 (x41, x42, x1, Arg1 (2));
   Mulx_U64 (x43, x44, x1, Arg1 (1));
   Mulx_U64 (x45, x46, x1, Arg1 (0));

   Addcarryx_U64 (x47, x48, 0, x46, x43);
   Addcarryx_U64 (x49, x50, x48, x44, x41);
   Addcarryx_U64 (x51, x52, x50, x42, x39);
   x53 := x52 + x40;

   Addcarryx_U64 (x54, x55, 0, x31, x45);
   Addcarryx_U64 (x56, x57, x55, x33, x47);
   Addcarryx_U64 (x58, x59, x57, x35, x49);
   Addcarryx_U64 (x60, x61, x59, x37, x51);
   Addcarryx_U64 (x62, x63, x61, x38, x53);

   -- Montgomery reduction 2
   Mulx_U64 (x64, x65, x54, 16#FFFF_FFFF_0000_0001#);
   Mulx_U64 (x66, x67, x54, 16#0000_0000_FFFF_FFFF#);
   Mulx_U64 (x68, x69, x54, 16#FFFF_FFFF_FFFF_FFFF#);

   Addcarryx_U64 (x70, x71, 0, x69, x66);
   x72 := x71 + x67;

   Addcarryx_U64 (x73, x74, 0, x54, x68);
   Addcarryx_U64 (x75, x76, x74, x56, x70);
   Addcarryx_U64 (x77, x78, x76, x58, x72);
   Addcarryx_U64 (x79, x80, x78, x60, x64);
   Addcarryx_U64 (x81, x82, x80, x62, x65);
   x83 := x82 + x63;

   -- Round 3: multiply by x2 = arg1[2]
   Mulx_U64 (x84, x85, x2, Arg1 (3));
   Mulx_U64 (x86, x87, x2, Arg1 (2));
   Mulx_U64 (x88, x89, x2, Arg1 (1));
   Mulx_U64 (x90, x91, x2, Arg1 (0));

   Addcarryx_U64 (x92, x93, 0, x91, x88);
   Addcarryx_U64 (x94, x95, x93, x89, x86);
   Addcarryx_U64 (x96, x97, x95, x87, x84);
   x98 := x97 + x85;

   Addcarryx_U64 (x99, x100, 0, x75, x90);
   Addcarryx_U64 (x101, x102, x100, x77, x92);
   Addcarryx_U64 (x103, x104, x102, x79, x94);
   Addcarryx_U64 (x105, x106, x104, x81, x96);
   Addcarryx_U64 (x107, x108, x106, x83, x98);

   -- Montgomery reduction 3
   Mulx_U64 (x109, x110, x99, 16#FFFF_FFFF_0000_0001#);
   Mulx_U64 (x111, x112, x99, 16#0000_0000_FFFF_FFFF#);
   Mulx_U64 (x113, x114, x99, 16#FFFF_FFFF_FFFF_FFFF#);

   Addcarryx_U64 (x115, x116, 0, x114, x111);
   x117 := x116 + x112;

   Addcarryx_U64 (x118, x119, 0, x99, x113);
   Addcarryx_U64 (x120, x121, x119, x101, x115);
   Addcarryx_U64 (x122, x123, x121, x103, x117);
   Addcarryx_U64 (x124, x125, x123, x105, x109);
   Addcarryx_U64 (x126, x127, x125, x107, x110);
   x128 := x127 + x108;

   -- Round 4: multiply by x3 = arg1[3]
   Mulx_U64 (x129, x130, x3, Arg1 (3));
   Mulx_U64 (x131, x132, x3, Arg1 (2));
   Mulx_U64 (x133, x134, x3, Arg1 (1));
   Mulx_U64 (x135, x136, x3, Arg1 (0));

   Addcarryx_U64 (x137, x138, 0, x136, x133);
   Addcarryx_U64 (x139, x140, x138, x134, x131);
   Addcarryx_U64 (x141, x142, x140, x132, x129);
   x143 := x142 + x130;

   Addcarryx_U64 (x144, x145, 0, x120, x135);
   Addcarryx_U64 (x146, x147, x145, x122, x137);
   Addcarryx_U64 (x148, x149, x147, x124, x139);
   Addcarryx_U64 (x150, x151, x149, x126, x141);
   Addcarryx_U64 (x152, x153, x151, x128, x143);

   -- Montgomery reduction 4
   Mulx_U64 (x154, x155, x144, 16#FFFF_FFFF_0000_0001#);
   Mulx_U64 (x156, x157, x144, 16#0000_0000_FFFF_FFFF#);
   Mulx_U64 (x158, x159, x144, 16#FFFF_FFFF_FFFF_FFFF#);

   Addcarryx_U64 (x160, x161, 0, x159, x156);
   x162 := x161 + x157;

   Addcarryx_U64 (x163, x164, 0, x144, x158);
   Addcarryx_U64 (x165, x166, x164, x146, x160);
   Addcarryx_U64 (x167, x168, x166, x148, x162);
   Addcarryx_U64 (x169, x170, x168, x150, x154);
   Addcarryx_U64 (x171, x172, x170, x152, x155);
   x173 := x172 + x153;

   -- Final conditional subtraction of p
   Subborrowx_U64 (x174, x175, 0, x165, 16#FFFF_FFFF_FFFF_FFFF#);
   Subborrowx_U64 (x176, x177, x175, x167, 16#0000_0000_FFFF_FFFF#);
   Subborrowx_U64 (x178, x179, x177, x169, 0);
   Subborrowx_U64 (x180, x181, x179, x171, 16#FFFF_FFFF_0000_0001#);
   Subborrowx_U64 (x182, x183, x181, x173, 0);

   -- Conditional move
   Cmovznz_U64 (x184, x183, x174, x165);
   Cmovznz_U64 (x185, x183, x176, x167);
   Cmovznz_U64 (x186, x183, x178, x169);
   Cmovznz_U64 (x187, x183, x180, x171);

   Out1 := (x184, x185, x186, x187);
   return Out1;
end Sqr;

   --  add: out1 := arg1 + arg2 mod p
   function Add (Arg1, Arg2 : FE) return FE is
      Out1 : FE;
      x1, x2, x3, x4, x5, x6, x7, x8   : Unsigned_64;
      x9, x10, x11, x12, x13, x14, x15, x16 : Unsigned_64;
      x17, x18, x19, x20, x21, x22      : Unsigned_64;
   begin
      --  4-limb addition with carry
      Addcarryx_U64 (x1, x2, 0, Arg1 (0), Arg2 (0));
      Addcarryx_U64 (x3, x4, x2, Arg1 (1), Arg2 (1));
      Addcarryx_U64 (x5, x6, x4, Arg1 (2), Arg2 (2));
      Addcarryx_U64 (x7, x8, x6, Arg1 (3), Arg2 (3));
      --  Tentatively subtract p
      Subborrowx_U64 (x9, x10, 0, x1, 16#FFFF_FFFF_FFFF_FFFF#);
      Subborrowx_U64 (x11, x12, x10, x3, 16#0000_0000_FFFF_FFFF#);
      Subborrowx_U64 (x13, x14, x12, x5, 0);
      Subborrowx_U64 (x15, x16, x14, x7, 16#FFFF_FFFF_0000_0001#);
      Subborrowx_U64 (x17, x18, x16, x8, 0);
      --  Conditional select: if borrow, keep sum; else keep subtracted
      declare Mask : constant Unsigned_64 := -(x18 and 1); begin
         x19 := (Mask and x1) or ((not Mask) and x9);
      end;
      declare Mask : constant Unsigned_64 := -(x18 and 1); begin
         x20 := (Mask and x3) or ((not Mask) and x11);
      end;
      declare Mask : constant Unsigned_64 := -(x18 and 1); begin
         x21 := (Mask and x5) or ((not Mask) and x13);
      end;
      declare Mask : constant Unsigned_64 := -(x18 and 1); begin
         x22 := (Mask and x7) or ((not Mask) and x15);
      end;
      Out1 := (x19, x20, x21, x22);
      return Out1;
   end Add;

   --  sub: out1 := arg1 - arg2 mod p
   function Sub (Arg1, Arg2 : FE) return FE is
      Out1 : FE;
      x1, x2, x3, x4, x5, x6, x7, x8 : Unsigned_64;
      x9, x10, x11, x12, x13, x14, x15, x16, x17 : Unsigned_64;
   begin
      --  4-limb subtraction with borrow
      Subborrowx_U64 (x1, x2, 0, Arg1 (0), Arg2 (0));
      Subborrowx_U64 (x3, x4, x2, Arg1 (1), Arg2 (1));
      Subborrowx_U64 (x5, x6, x4, Arg1 (2), Arg2 (2));
      Subborrowx_U64 (x7, x8, x6, Arg1 (3), Arg2 (3));
      --  If borrow, add p back (conditional on x8)
      declare Mask : constant Unsigned_64 := -(x8 and 1); begin
         x9 := Mask and 16#FFFF_FFFF_FFFF_FFFF#;  --  = 0 or p[0]
      end;
      Addcarryx_U64 (x10, x11, 0, x1, x9);
      Addcarryx_U64 (x12, x13, x11, x3, x9 and 16#0000_0000_FFFF_FFFF#);
      Addcarryx_U64 (x14, x15, x13, x5, 0);
      Addcarryx_U64 (x16, x17, x15, x7, x9 and 16#FFFF_FFFF_0000_0001#);
      Out1 := (x10, x12, x14, x16);
      return Out1;
   end Sub;

   --  opp: out1 := -arg1 mod p
   function Opp (Arg1 : FE) return FE is
      Out1 : FE;
      x1, x2, x3, x4, x5, x6, x7, x8 : Unsigned_64;
      x9, x10, x11, x12, x13, x14, x15, x16, x17 : Unsigned_64;
   begin
      --  Subtract arg1 from 0 with borrow chain
      Subborrowx_U64 (x1, x2, 0, 0, Arg1 (0));
      Subborrowx_U64 (x3, x4, x2, 0, Arg1 (1));
      Subborrowx_U64 (x5, x6, x4, 0, Arg1 (2));
      Subborrowx_U64 (x7, x8, x6, 0, Arg1 (3));
      --  Conditionally add p
      declare Mask : constant Unsigned_64 := -(x8 and 1); begin
         x9 := Mask and 16#FFFF_FFFF_FFFF_FFFF#;
      end;
      Addcarryx_U64 (x10, x11, 0, x1, x9);
      Addcarryx_U64 (x12, x13, x11, x3, x9 and 16#0000_0000_FFFF_FFFF#);
      Addcarryx_U64 (x14, x15, x13, x5, 0);
      Addcarryx_U64 (x16, x17, x15, x7, x9 and 16#FFFF_FFFF_0000_0001#);
      Out1 := (x10, x12, x14, x16);
      return Out1;
   end Opp;

   --  selectznz: constant-time conditional select
   function Selectznz (Cond : Unsigned_64;
                        Arg2, Arg3 : FE) return FE is
      Out1 : FE;
      Mask : constant Unsigned_64 := -(Cond and 1);
   begin
      --  if Cond = 0, select Arg2; else select Arg3
      Out1 := ((Mask and Arg3 (0)) or ((not Mask) and Arg2 (0)),
               (Mask and Arg3 (1)) or ((not Mask) and Arg2 (1)),
               (Mask and Arg3 (2)) or ((not Mask) and Arg2 (2)),
               (Mask and Arg3 (3)) or ((not Mask) and Arg2 (3)));
      return Out1;
   end Selectznz;

   --  nonzero
   procedure Nonzero (Out1 : out Unsigned_64; Arg1 : FE) is
   begin
      Out1 := Arg1 (0) or Arg1 (1) or Arg1 (2) or Arg1 (3);
   end Nonzero;

   --  to_bytes: field element to 32 little-endian bytes
   procedure To_Bytes (Out1 : out Byte_Seq; Arg1 : FE) is
      F : constant I32 := Out1'First;
   begin
      Out1 := (others => 0);
      for Limb_Idx in 0 .. 3 loop
         declare
            V : Unsigned_64 := Arg1 (Limb_Idx);
            Base : constant I32 := F + I32 (Limb_Idx) * 8;
         begin
            for B in 0 .. 7 loop
               Out1 (Base + I32 (B)) := Byte (V and 16#FF#);
               V := Shift_Right (V, 8);
            end loop;
         end;
      end loop;
   end To_Bytes;

   --  from_bytes: 32 little-endian bytes to field element
   function From_Bytes (Arg1 : Byte_Seq) return FE is
      Out1 : FE;
      F : constant I32 := Arg1'First;
   begin
      for Limb_Idx in 0 .. 3 loop
         declare
            V : Unsigned_64 := 0;
            Base : constant I32 := F + I32 (Limb_Idx) * 8;
         begin
            for B in reverse 0 .. 7 loop
               V := Shift_Left (V, 8) or Unsigned_64 (Arg1 (Base + I32 (B)));
            end loop;
            Out1 (Limb_Idx) := V;
         end;
      end loop;
      return Out1;
   end From_Bytes;

   --  from_montgomery / to_montgomery
   --  Translated from fiat_p256_64.c lines 921-1340

   function From_Montgomery (Arg1 : FE) return FE is
   Out1 : FE;
   x1, x2, x3, x4, x5, x6, x7, x8 : Unsigned_64;
   x9, x10, x11, x12, x13, x14, x15, x16 : Unsigned_64;
   x17, x18, x19, x20, x21, x22, x23, x24 : Unsigned_64;
   x25, x26, x27, x28, x29, x30, x31, x32 : Unsigned_64;
   x33, x34, x35, x36, x37, x38, x39, x40 : Unsigned_64;
   x41, x42, x43, x44, x45, x46, x47, x48 : Unsigned_64;
   x49, x50, x51, x52, x53, x54, x55, x56 : Unsigned_64;
   x57, x58, x59, x60, x61, x62, x63, x64 : Unsigned_64;
   x65, x66, x67, x68, x69, x70, x71, x72 : Unsigned_64;
   x73, x74, x75, x76, x77, x78, x79, x80 : Unsigned_64;
   x81, x82, x83, x84, x85, x86, x87, x88 : Unsigned_64;
   x89, x90 : Unsigned_64;
begin
   --  Round 1: arg1[0]
   x1 := Arg1 (0);

   --  mulx_u64(&x2, &x3, x1, 0xffffffff00000001)
   Mulx_U64 (x2, x3, x1, 16#FFFF_FFFF_0000_0001#);

   --  mulx_u64(&x4, &x5, x1, 0xffffffff)
   Mulx_U64 (x4, x5, x1, 16#FFFF_FFFF#);

   --  mulx_u64(&x6, &x7, x1, 0xffffffffffffffff)
   Mulx_U64 (x6, x7, x1, 16#FFFF_FFFF_FFFF_FFFF#);

   --  addcarryx_u64(&x8, &x9, 0x0, x7, x4)
   Addcarryx_U64 (x8, x9, 0, x7, x4);

   --  addcarryx_u64(&x10, &x11, 0x0, x1, x6)
   Addcarryx_U64 (x10, x11, 0, x1, x6);

   --  addcarryx_u64(&x12, &x13, x11, 0x0, x8)
   Addcarryx_U64 (x12, x13, x11, 0, x8);

   --  addcarryx_u64(&x14, &x15, 0x0, x12, arg1[1])
   Addcarryx_U64 (x14, x15, 0, x12, Arg1 (1));

   --  Round 2: x14
   --  mulx_u64(&x16, &x17, x14, 0xffffffff00000001)
   Mulx_U64 (x16, x17, x14, 16#FFFF_FFFF_0000_0001#);

   --  mulx_u64(&x18, &x19, x14, 0xffffffff)
   Mulx_U64 (x18, x19, x14, 16#FFFF_FFFF#);

   --  mulx_u64(&x20, &x21, x14, 0xffffffffffffffff)
   Mulx_U64 (x20, x21, x14, 16#FFFF_FFFF_FFFF_FFFF#);

   --  addcarryx_u64(&x22, &x23, 0x0, x21, x18)
   Addcarryx_U64 (x22, x23, 0, x21, x18);

   --  addcarryx_u64(&x24, &x25, 0x0, x14, x20)
   Addcarryx_U64 (x24, x25, 0, x14, x20);

   --  addcarryx_u64(&x26, &x27, x25, (x15 + (x13 + (x9 + x5))), x22)
   declare
      T_26 : constant Unsigned_128 := Unsigned_128 (x25) + Unsigned_128 (x15 + (x13 + (x9 + x5))) + Unsigned_128 (x22);
   begin
      x26 := Unsigned_64 (T_26 and 16#FFFF_FFFF_FFFF_FFFF#);
      x27 := Unsigned_64 (Shift_Right (T_26, 64));
   end;

   --  addcarryx_u64(&x28, &x29, x27, x2, (x23 + x19))
   Addcarryx_U64 (x28, x29, x27, x2, x23 + x19);

   --  addcarryx_u64(&x30, &x31, x29, x3, x16)
   Addcarryx_U64 (x30, x31, x29, x3, x16);

   --  addcarryx_u64(&x32, &x33, 0x0, x26, arg1[2])
   Addcarryx_U64 (x32, x33, 0, x26, Arg1 (2));

   --  addcarryx_u64(&x34, &x35, x33, x28, 0x0)
   Addcarryx_U64 (x34, x35, x33, x28, 0);

   --  addcarryx_u64(&x36, &x37, x35, x30, 0x0)
   Addcarryx_U64 (x36, x37, x35, x30, 0);

   --  Round 3: x32
   --  mulx_u64(&x38, &x39, x32, 0xffffffff00000001)
   Mulx_U64 (x38, x39, x32, 16#FFFF_FFFF_0000_0001#);

   --  mulx_u64(&x40, &x41, x32, 0xffffffff)
   Mulx_U64 (x40, x41, x32, 16#FFFF_FFFF#);

   --  mulx_u64(&x42, &x43, x32, 0xffffffffffffffff)
   Mulx_U64 (x42, x43, x32, 16#FFFF_FFFF_FFFF_FFFF#);

   --  addcarryx_u64(&x44, &x45, 0x0, x43, x40)
   Addcarryx_U64 (x44, x45, 0, x43, x40);

   --  addcarryx_u64(&x46, &x47, 0x0, x32, x42)
   Addcarryx_U64 (x46, x47, 0, x32, x42);

   --  addcarryx_u64(&x48, &x49, x47, x34, x44)
   Addcarryx_U64 (x48, x49, x47, x34, x44);

   --  addcarryx_u64(&x50, &x51, x49, x36, (x45 + x41))
   Addcarryx_U64 (x50, x51, x49, x36, x45 + x41);

   --  addcarryx_u64(&x52, &x53, x51, (x37 + (x31 + x17)), x38)
   Addcarryx_U64 (x52, x53, x51, x37 + (x31 + x17), x38);

   --  addcarryx_u64(&x54, &x55, 0x0, x48, arg1[3])
   Addcarryx_U64 (x54, x55, 0, x48, Arg1 (3));

   --  addcarryx_u64(&x56, &x57, x55, x50, 0x0)
   Addcarryx_U64 (x56, x57, x55, x50, 0);

   --  addcarryx_u64(&x58, &x59, x57, x52, 0x0)
   Addcarryx_U64 (x58, x59, x57, x52, 0);

   --  Round 4: x54
   --  mulx_u64(&x60, &x61, x54, 0xffffffff00000001)
   Mulx_U64 (x60, x61, x54, 16#FFFF_FFFF_0000_0001#);

   --  mulx_u64(&x62, &x63, x54, 0xffffffff)
   Mulx_U64 (x62, x63, x54, 16#FFFF_FFFF#);

   --  mulx_u64(&x64, &x65, x54, 0xffffffffffffffff)
   Mulx_U64 (x64, x65, x54, 16#FFFF_FFFF_FFFF_FFFF#);

   --  addcarryx_u64(&x66, &x67, 0x0, x65, x62)
   Addcarryx_U64 (x66, x67, 0, x65, x62);

   --  addcarryx_u64(&x68, &x69, 0x0, x54, x64)
   Addcarryx_U64 (x68, x69, 0, x54, x64);

   --  addcarryx_u64(&x70, &x71, x69, x56, x66)
   Addcarryx_U64 (x70, x71, x69, x56, x66);

   --  addcarryx_u64(&x72, &x73, x71, x58, (x67 + x63))
   Addcarryx_U64 (x72, x73, x71, x58, x67 + x63);

   --  addcarryx_u64(&x74, &x75, x73, (x59 + (x53 + x39)), x60)
   Addcarryx_U64 (x74, x75, x73, x59 + (x53 + x39), x60);

   --  x76 = (x75 + x61)
   x76 := x75 + x61;

   --  Conditional subtraction of p
   --  subborrowx_u64(&x77, &x78, 0x0, x70, 0xffffffffffffffff)
   Subborrowx_U64 (x77, x78, 0, x70, 16#FFFF_FFFF_FFFF_FFFF#);

   --  subborrowx_u64(&x79, &x80, x78, x72, 0xffffffff)
   Subborrowx_U64 (x79, x80, x78, x72, 16#FFFF_FFFF#);

   --  subborrowx_u64(&x81, &x82, x80, x74, 0x0)
   Subborrowx_U64 (x81, x82, x80, x74, 0);

   --  subborrowx_u64(&x83, &x84, x82, x76, 0xffffffff00000001)
   Subborrowx_U64 (x83, x84, x82, x76, 16#FFFF_FFFF_0000_0001#);

   --  subborrowx_u64(&x85, &x86, x84, 0x0, 0x0)
   Subborrowx_U64 (x85, x86, x84, 0, 0);

   --  cmovznz_u64(&x87, x86, x77, x70)
   Cmovznz_U64 (x87, x86, x77, x70);

   --  cmovznz_u64(&x88, x86, x79, x72)
   Cmovznz_U64 (x88, x86, x79, x72);

   --  cmovznz_u64(&x89, x86, x81, x74)
   Cmovznz_U64 (x89, x86, x81, x74);

   --  cmovznz_u64(&x90, x86, x83, x76)
   Cmovznz_U64 (x90, x86, x83, x76);

   Out1 := (x87, x88, x89, x90);
   return Out1;
end From_Montgomery;

------------------------------------------------------------------------

function To_Montgomery (Arg1 : FE) return FE is
   Out1 : FE;
   x1, x2, x3, x4, x5, x6, x7, x8 : Unsigned_64;
   x9, x10, x11, x12, x13, x14, x15, x16 : Unsigned_64;
   x17, x18, x19, x20, x21, x22, x23, x24 : Unsigned_64;
   x25, x26, x27, x28, x29, x30, x31, x32 : Unsigned_64;
   x33, x34, x35, x36, x37, x38, x39, x40 : Unsigned_64;
   x41, x42, x43, x44, x45, x46, x47, x48 : Unsigned_64;
   x49, x50, x51, x52, x53, x54, x55, x56 : Unsigned_64;
   x57, x58, x59, x60, x61, x62, x63, x64 : Unsigned_64;
   x65, x66, x67, x68, x69, x70, x71, x72 : Unsigned_64;
   x73, x74, x75, x76, x77, x78, x79, x80 : Unsigned_64;
   x81, x82, x83, x84, x85, x86, x87, x88 : Unsigned_64;
   x89, x90, x91, x92, x93, x94, x95, x96 : Unsigned_64;
   x97, x98, x99, x100, x101, x102, x103, x104 : Unsigned_64;
   x105, x106, x107, x108, x109, x110, x111, x112 : Unsigned_64;
   x113, x114, x115, x116, x117, x118, x119, x120 : Unsigned_64;
   x121, x122, x123, x124, x125, x126, x127, x128 : Unsigned_64;
   x129, x130, x131, x132, x133, x134, x135, x136 : Unsigned_64;
   x137, x138, x139, x140, x141, x142, x143, x144 : Unsigned_64;
   x145, x146, x147, x148, x149, x150, x151, x152 : Unsigned_64;
   x153, x154, x155, x156, x157, x158, x159, x160 : Unsigned_64;
   x161, x162, x163, x164, x165, x166, x167, x168 : Unsigned_64;
   x169, x170 : Unsigned_64;
begin
   x1 := Arg1 (1);
   x2 := Arg1 (2);
   x3 := Arg1 (3);
   x4 := Arg1 (0);

   --  Round 1: multiply x4 by R^2 mod p constants
   --  mulx_u64(&x5, &x6, x4, 0x4fffffffd)
   Mulx_U64 (x5, x6, x4, 16#4_FFFF_FFFD#);

   --  mulx_u64(&x7, &x8, x4, 0xfffffffffffffffe)
   Mulx_U64 (x7, x8, x4, 16#FFFF_FFFF_FFFF_FFFE#);

   --  mulx_u64(&x9, &x10, x4, 0xfffffffbffffffff)
   Mulx_U64 (x9, x10, x4, 16#FFFF_FFFB_FFFF_FFFF#);

   --  mulx_u64(&x11, &x12, x4, 0x3)
   Mulx_U64 (x11, x12, x4, 16#3#);

   --  addcarryx_u64(&x13, &x14, 0x0, x12, x9)
   Addcarryx_U64 (x13, x14, 0, x12, x9);

   --  addcarryx_u64(&x15, &x16, x14, x10, x7)
   Addcarryx_U64 (x15, x16, x14, x10, x7);

   --  addcarryx_u64(&x17, &x18, x16, x8, x5)
   Addcarryx_U64 (x17, x18, x16, x8, x5);

   --  Montgomery reduction round 1
   --  mulx_u64(&x19, &x20, x11, 0xffffffff00000001)
   Mulx_U64 (x19, x20, x11, 16#FFFF_FFFF_0000_0001#);

   --  mulx_u64(&x21, &x22, x11, 0xffffffff)
   Mulx_U64 (x21, x22, x11, 16#FFFF_FFFF#);

   --  mulx_u64(&x23, &x24, x11, 0xffffffffffffffff)
   Mulx_U64 (x23, x24, x11, 16#FFFF_FFFF_FFFF_FFFF#);

   --  addcarryx_u64(&x25, &x26, 0x0, x24, x21)
   Addcarryx_U64 (x25, x26, 0, x24, x21);

   --  addcarryx_u64(&x27, &x28, 0x0, x11, x23)
   Addcarryx_U64 (x27, x28, 0, x11, x23);

   --  addcarryx_u64(&x29, &x30, x28, x13, x25)
   Addcarryx_U64 (x29, x30, x28, x13, x25);

   --  addcarryx_u64(&x31, &x32, x30, x15, (x26 + x22))
   Addcarryx_U64 (x31, x32, x30, x15, x26 + x22);

   --  addcarryx_u64(&x33, &x34, x32, x17, x19)
   Addcarryx_U64 (x33, x34, x32, x17, x19);

   --  addcarryx_u64(&x35, &x36, x34, (x18 + x6), x20)
   Addcarryx_U64 (x35, x36, x34, x18 + x6, x20);

   --  Round 2: multiply x1 by R^2 mod p constants
   --  mulx_u64(&x37, &x38, x1, 0x4fffffffd)
   Mulx_U64 (x37, x38, x1, 16#4_FFFF_FFFD#);

   --  mulx_u64(&x39, &x40, x1, 0xfffffffffffffffe)
   Mulx_U64 (x39, x40, x1, 16#FFFF_FFFF_FFFF_FFFE#);

   --  mulx_u64(&x41, &x42, x1, 0xfffffffbffffffff)
   Mulx_U64 (x41, x42, x1, 16#FFFF_FFFB_FFFF_FFFF#);

   --  mulx_u64(&x43, &x44, x1, 0x3)
   Mulx_U64 (x43, x44, x1, 16#3#);

   --  addcarryx_u64(&x45, &x46, 0x0, x44, x41)
   Addcarryx_U64 (x45, x46, 0, x44, x41);

   --  addcarryx_u64(&x47, &x48, x46, x42, x39)
   Addcarryx_U64 (x47, x48, x46, x42, x39);

   --  addcarryx_u64(&x49, &x50, x48, x40, x37)
   Addcarryx_U64 (x49, x50, x48, x40, x37);

   --  addcarryx_u64(&x51, &x52, 0x0, x29, x43)
   Addcarryx_U64 (x51, x52, 0, x29, x43);

   --  addcarryx_u64(&x53, &x54, x52, x31, x45)
   Addcarryx_U64 (x53, x54, x52, x31, x45);

   --  addcarryx_u64(&x55, &x56, x54, x33, x47)
   Addcarryx_U64 (x55, x56, x54, x33, x47);

   --  addcarryx_u64(&x57, &x58, x56, x35, x49)
   Addcarryx_U64 (x57, x58, x56, x35, x49);

   --  Montgomery reduction round 2
   --  mulx_u64(&x59, &x60, x51, 0xffffffff00000001)
   Mulx_U64 (x59, x60, x51, 16#FFFF_FFFF_0000_0001#);

   --  mulx_u64(&x61, &x62, x51, 0xffffffff)
   Mulx_U64 (x61, x62, x51, 16#FFFF_FFFF#);

   --  mulx_u64(&x63, &x64, x51, 0xffffffffffffffff)
   Mulx_U64 (x63, x64, x51, 16#FFFF_FFFF_FFFF_FFFF#);

   --  addcarryx_u64(&x65, &x66, 0x0, x64, x61)
   Addcarryx_U64 (x65, x66, 0, x64, x61);

   --  addcarryx_u64(&x67, &x68, 0x0, x51, x63)
   Addcarryx_U64 (x67, x68, 0, x51, x63);

   --  addcarryx_u64(&x69, &x70, x68, x53, x65)
   Addcarryx_U64 (x69, x70, x68, x53, x65);

   --  addcarryx_u64(&x71, &x72, x70, x55, (x66 + x62))
   Addcarryx_U64 (x71, x72, x70, x55, x66 + x62);

   --  addcarryx_u64(&x73, &x74, x72, x57, x59)
   Addcarryx_U64 (x73, x74, x72, x57, x59);

   --  addcarryx_u64(&x75, &x76, x74, (((uint64_t)x58 + x36) + (x50 + x38)), x60)
   Addcarryx_U64 (x75, x76, x74, (x58 + x36) + (x50 + x38), x60);

   --  Round 3: multiply x2 by R^2 mod p constants
   --  mulx_u64(&x77, &x78, x2, 0x4fffffffd)
   Mulx_U64 (x77, x78, x2, 16#4_FFFF_FFFD#);

   --  mulx_u64(&x79, &x80, x2, 0xfffffffffffffffe)
   Mulx_U64 (x79, x80, x2, 16#FFFF_FFFF_FFFF_FFFE#);

   --  mulx_u64(&x81, &x82, x2, 0xfffffffbffffffff)
   Mulx_U64 (x81, x82, x2, 16#FFFF_FFFB_FFFF_FFFF#);

   --  mulx_u64(&x83, &x84, x2, 0x3)
   Mulx_U64 (x83, x84, x2, 16#3#);

   --  addcarryx_u64(&x85, &x86, 0x0, x84, x81)
   Addcarryx_U64 (x85, x86, 0, x84, x81);

   --  addcarryx_u64(&x87, &x88, x86, x82, x79)
   Addcarryx_U64 (x87, x88, x86, x82, x79);

   --  addcarryx_u64(&x89, &x90, x88, x80, x77)
   Addcarryx_U64 (x89, x90, x88, x80, x77);

   --  addcarryx_u64(&x91, &x92, 0x0, x69, x83)
   Addcarryx_U64 (x91, x92, 0, x69, x83);

   --  addcarryx_u64(&x93, &x94, x92, x71, x85)
   Addcarryx_U64 (x93, x94, x92, x71, x85);

   --  addcarryx_u64(&x95, &x96, x94, x73, x87)
   Addcarryx_U64 (x95, x96, x94, x73, x87);

   --  addcarryx_u64(&x97, &x98, x96, x75, x89)
   Addcarryx_U64 (x97, x98, x96, x75, x89);

   --  Montgomery reduction round 3
   --  mulx_u64(&x99, &x100, x91, 0xffffffff00000001)
   Mulx_U64 (x99, x100, x91, 16#FFFF_FFFF_0000_0001#);

   --  mulx_u64(&x101, &x102, x91, 0xffffffff)
   Mulx_U64 (x101, x102, x91, 16#FFFF_FFFF#);

   --  mulx_u64(&x103, &x104, x91, 0xffffffffffffffff)
   Mulx_U64 (x103, x104, x91, 16#FFFF_FFFF_FFFF_FFFF#);

   --  addcarryx_u64(&x105, &x106, 0x0, x104, x101)
   Addcarryx_U64 (x105, x106, 0, x104, x101);

   --  addcarryx_u64(&x107, &x108, 0x0, x91, x103)
   Addcarryx_U64 (x107, x108, 0, x91, x103);

   --  addcarryx_u64(&x109, &x110, x108, x93, x105)
   Addcarryx_U64 (x109, x110, x108, x93, x105);

   --  addcarryx_u64(&x111, &x112, x110, x95, (x106 + x102))
   Addcarryx_U64 (x111, x112, x110, x95, x106 + x102);

   --  addcarryx_u64(&x113, &x114, x112, x97, x99)
   Addcarryx_U64 (x113, x114, x112, x97, x99);

   --  addcarryx_u64(&x115, &x116, x114, (((uint64_t)x98 + x76) + (x90 + x78)), x100)
   Addcarryx_U64 (x115, x116, x114, (x98 + x76) + (x90 + x78), x100);

   --  Round 4: multiply x3 by R^2 mod p constants
   --  mulx_u64(&x117, &x118, x3, 0x4fffffffd)
   Mulx_U64 (x117, x118, x3, 16#4_FFFF_FFFD#);

   --  mulx_u64(&x119, &x120, x3, 0xfffffffffffffffe)
   Mulx_U64 (x119, x120, x3, 16#FFFF_FFFF_FFFF_FFFE#);

   --  mulx_u64(&x121, &x122, x3, 0xfffffffbffffffff)
   Mulx_U64 (x121, x122, x3, 16#FFFF_FFFB_FFFF_FFFF#);

   --  mulx_u64(&x123, &x124, x3, 0x3)
   Mulx_U64 (x123, x124, x3, 16#3#);

   --  addcarryx_u64(&x125, &x126, 0x0, x124, x121)
   Addcarryx_U64 (x125, x126, 0, x124, x121);

   --  addcarryx_u64(&x127, &x128, x126, x122, x119)
   Addcarryx_U64 (x127, x128, x126, x122, x119);

   --  addcarryx_u64(&x129, &x130, x128, x120, x117)
   Addcarryx_U64 (x129, x130, x128, x120, x117);

   --  addcarryx_u64(&x131, &x132, 0x0, x109, x123)
   Addcarryx_U64 (x131, x132, 0, x109, x123);

   --  addcarryx_u64(&x133, &x134, x132, x111, x125)
   Addcarryx_U64 (x133, x134, x132, x111, x125);

   --  addcarryx_u64(&x135, &x136, x134, x113, x127)
   Addcarryx_U64 (x135, x136, x134, x113, x127);

   --  addcarryx_u64(&x137, &x138, x136, x115, x129)
   Addcarryx_U64 (x137, x138, x136, x115, x129);

   --  Montgomery reduction round 4
   --  mulx_u64(&x139, &x140, x131, 0xffffffff00000001)
   Mulx_U64 (x139, x140, x131, 16#FFFF_FFFF_0000_0001#);

   --  mulx_u64(&x141, &x142, x131, 0xffffffff)
   Mulx_U64 (x141, x142, x131, 16#FFFF_FFFF#);

   --  mulx_u64(&x143, &x144, x131, 0xffffffffffffffff)
   Mulx_U64 (x143, x144, x131, 16#FFFF_FFFF_FFFF_FFFF#);

   --  addcarryx_u64(&x145, &x146, 0x0, x144, x141)
   Addcarryx_U64 (x145, x146, 0, x144, x141);

   --  addcarryx_u64(&x147, &x148, 0x0, x131, x143)
   Addcarryx_U64 (x147, x148, 0, x131, x143);

   --  addcarryx_u64(&x149, &x150, x148, x133, x145)
   Addcarryx_U64 (x149, x150, x148, x133, x145);

   --  addcarryx_u64(&x151, &x152, x150, x135, (x146 + x142))
   Addcarryx_U64 (x151, x152, x150, x135, x146 + x142);

   --  addcarryx_u64(&x153, &x154, x152, x137, x139)
   Addcarryx_U64 (x153, x154, x152, x137, x139);

   --  addcarryx_u64(&x155, &x156, x154, (((uint64_t)x138 + x116) + (x130 + x118)), x140)
   Addcarryx_U64 (x155, x156, x154, (x138 + x116) + (x130 + x118), x140);

   --  Conditional subtraction of p
   --  subborrowx_u64(&x157, &x158, 0x0, x149, 0xffffffffffffffff)
   Subborrowx_U64 (x157, x158, 0, x149, 16#FFFF_FFFF_FFFF_FFFF#);

   --  subborrowx_u64(&x159, &x160, x158, x151, 0xffffffff)
   Subborrowx_U64 (x159, x160, x158, x151, 16#FFFF_FFFF#);

   --  subborrowx_u64(&x161, &x162, x160, x153, 0x0)
   Subborrowx_U64 (x161, x162, x160, x153, 0);

   --  subborrowx_u64(&x163, &x164, x162, x155, 0xffffffff00000001)
   Subborrowx_U64 (x163, x164, x162, x155, 16#FFFF_FFFF_0000_0001#);

   --  subborrowx_u64(&x165, &x166, x164, x156, 0x0)
   Subborrowx_U64 (x165, x166, x164, x156, 0);

   --  cmovznz_u64(&x167, x166, x157, x149)
   Cmovznz_U64 (x167, x166, x157, x149);

   --  cmovznz_u64(&x168, x166, x159, x151)
   Cmovznz_U64 (x168, x166, x159, x151);

   --  cmovznz_u64(&x169, x166, x161, x153)
   Cmovznz_U64 (x169, x166, x161, x153);

   --  cmovznz_u64(&x170, x166, x163, x155)
   Cmovznz_U64 (x170, x166, x163, x155);

   Out1 := (x167, x168, x169, x170);
   return Out1;
end To_Montgomery;

end SPARKTLSCrypto.Fiat_P256;
